name: stress-ng
base: core24 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A stress-ng snap
description: |
  A stress-ng snap
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  stress-ng:
    command: usr/bin/stress-ng

parts:
  stress-ng:
    # See 'snapcraft plugins'
    plugin: nil
    stage-packages: [stress-ng]
